In [1]:
from heavystats.cleaning import load_data

df = load_data()

In [2]:
import heavystats as hs
print(hs.__version__)

0.1.0

In [3]:
from heavystats.validation import validate_data
validate_data(df)

In [4]:
df["Edad"].max(), df["Edad"].min()

(np.int64(9), np.int64(5))

In [5]:
from heavystats.cleaning import columns_type

columns_type(df)

In [6]:
from heavystats.cleaning import categorical_columns, numerical_columns, variables_table

variables_table(df)

In [7]:
from heavystats.cleaning import get_analytical_sample

df_p = df
df_s = get_analytical_sample(df)

df_s.head()

,Muestra_Codificada,Edad,Sexo,Peso_kg,Altura_cm,Sector,Institucion,Es_Expuesto,Riesgo_Pb,Riesgo_Hg,...,Alim_Grasas,Alim_Chocolate,Salud_Fuma,Salud_Actividad,Salud_Bombillos,Salud_Techo,Salud_Joyeria,Salud_Transporte,Salud_Agua,Salud_Suplementos
0,1,7,femenino,32.0,128.0,Centro A,Santiago Mariño,NO,NO,NO,...,Rara vez,Nunca,No,Si,No,No,Si,Vehículo,Agua filtrada,Suplemento multivitamínico
1,2,8,masculino,21.0,125.0,Sur,Santiago Mariño,NO,SI,NO,...,Diario,Rara vez,Si,No,No,No,No,Caminar,Agua filtrada,Ninguno de los anteriores
2,3,9,masculino,31.0,141.0,Sur,Santiago Mariño,SI,SI,NO,...,Frecuentemente,Rara vez,No,Si,Si,No,No,Vehículo,Agua filtrada; Agua mineral embotellada,Suplemento multivitamínico
3,4,7,masculino,24.0,126.0,Centro C,Santiago Mariño,SI,SI,SI,...,Diario,A veces,Si,No,No,No,No,Caminar; Vehículo; Transporte público,Agua mineral embotellada,Suplemento multivitamínico
4,5,6,femenino,19.0,117.0,Centro B,Santiago Mariño,SI,SI,SI,...,A veces,Frecuentemente,No,Si,No,No,Si,Vehículo,Agua mineral embotellada,Ninguno de los anteriores

In [8]:
from heavystats.cleaning import select_metal

select_metal(df_s, "Pb")

,Muestra_Codificada,Edad,Sexo,Peso_kg,Altura_cm,Sector,Institucion,Es_Expuesto,Riesgo_Pb,Score_Riesgo,...,Alim_Grasas,Alim_Chocolate,Salud_Fuma,Salud_Actividad,Salud_Bombillos,Salud_Techo,Salud_Joyeria,Salud_Transporte,Salud_Agua,Salud_Suplementos
0,1,7,femenino,32.0,128.0,Centro A,Santiago Mariño,NO,NO,1,...,Rara vez,Nunca,No,Si,No,No,Si,Vehículo,Agua filtrada,Suplemento multivitamínico
1,2,8,masculino,21.0,125.0,Sur,Santiago Mariño,NO,SI,2,...,Diario,Rara vez,Si,No,No,No,No,Caminar,Agua filtrada,Ninguno de los anteriores
2,3,9,masculino,31.0,141.0,Sur,Santiago Mariño,SI,SI,5,...,Frecuentemente,Rara vez,No,Si,Si,No,No,Vehículo,Agua filtrada; Agua mineral embotellada,Suplemento multivitamínico
3,4,7,masculino,24.0,126.0,Centro C,Santiago Mariño,SI,SI,5,...,Diario,A veces,Si,No,No,No,No,Caminar; Vehículo; Transporte público,Agua mineral embotellada,Suplemento multivitamínico
4,5,6,femenino,19.0,117.0,Centro B,Santiago Mariño,SI,SI,4,...,A veces,Frecuentemente,No,Si,No,No,Si,Vehículo,Agua mineral embotellada,Ninguno de los anteriores
5,6,7,masculino,22.0,119.0,Centro A,Santiago Mariño,NO,SI,2,...,Frecuentemente,Nunca,No,No,Si,No,No,Caminar,Agua de pozo profundo,Ninguno de los anteriores
6,7,9,femenino,26.0,132.0,Sur,Santiago Mariño,SI,SI,5,...,A veces,Frecuentemente,Si,No,Si,No,No,Vehículo; Transporte público,Agua filtrada,Ninguno de los anteriores
7,8,7,masculino,19.0,118.0,Sur,Santiago Mariño,SI,SI,5,...,Diario,A veces,Si,No,Si,No,No,Caminar; Vehículo,Agua filtrada,Ninguno de los anteriores
8,9,6,masculino,21.0,121.0,Centro B,Santiago Mariño,NO,SI,1,...,Diario,A veces,No,No,No,No,No,Caminar; Vehículo; Transporte público,Agua filtrada,Ninguno de los anteriores
9,10,5,femenino,15.0,108.0,Sur,Santiago Mariño,NO,SI,2,...,Frecuentemente,Frecuentemente,Si,No,No,No,Si,Caminar,Agua filtrada,Ninguno de los anteriores
10,11,7,masculino,36.0,129.0,Centro B,Clorinda Azcunes,NO,SI,1,...,A veces,Rara vez,No,No,Si,No,No,Caminar; Vehículo; Transporte público,Agua mineral embotellada,Ninguno de los anteriores
11,12,9,masculino,20.0,134.0,Centro B,Clorinda Azcunes,NO,SI,1,...,A veces,Rara vez,No,No,Si,No,No,Caminar; Vehículo; Transporte público,Agua mineral embotellada,Suplemento multivitamínico
12,13,6,femenino,19.0,118.0,Centro A,Clorinda Azcunes,SI,NO,4,...,Nunca,Rara vez,Si,No,Si,No,No,Vehículo,Agua mineral embotellada,Ninguno de los anteriores
13,14,6,masculino,32.0,135.0,Centro A,Mons. Luis Eduardo Enrique,NO,NO,1,...,Nunca,A veces,No,Si,Si,No,No,Vehículo,Agua mineral embotellada,Suplemento multivitamínico
14,15,8,femenino,25.0,133.0,Centro A,Santiago Mariño,NO,SI,3,...,Frecuentemente,A veces,Si,No,Si,No,No,Vehículo,Agua de pozo profundo,Suplemento multivitamínico
15,16,7,masculino,28.0,132.0,Sur,Santiago Mariño,SI,SI,4,...,A veces,Nunca,No,No,Si,No,No,Caminar,Agua mineral embotellada,Suplemento multivitamínico
16,17,8,femenino,23.0,129.0,Centro A,Santiago Mariño,SI,SI,5,...,Frecuentemente,Diario,No,Si,Si,No,No,Vehículo,Agua de pozo profundo,Ninguno de los anteriores
17,18,9,masculino,38.0,140.0,Centro C,Santiago Mariño,SI,SI,4,...,Frecuentemente,Diario,No,Si,No,No,No,Caminar; Vehículo; Transporte público,Agua mineral embotellada,Suplemento multivitamínico
18,19,9,masculino,41.0,140.0,Norte B,Santiago Mariño,SI,SI,5,...,Frecuentemente,Rara vez,No,Si,No,No,No,Caminar; Vehículo; Transporte público,Agua mineral embotellada,Ninguno de los anteriores
19,20,8,masculino,30.0,135.0,Sur,Santiago Mariño,SI,SI,5,...,Frecuentemente,Frecuentemente,No,No,Si,No,No,Vehículo,Agua filtrada,Ninguno de los anteriores

In [9]:
import heavystats

# 1. Cargar el dataset original
df = heavystats.load_data()

# 2. Estandarizar Sí/No a SI/NO
df_procesado = heavystats.standardize_boolean_columns(df)

# 3. Desagregar respuestas múltiples (creará las columnas binarias _Caminar, _Vehiculo, etc.)
df_procesado = heavystats.desaggregate_multiple_responses(
    df_procesado, 
   columns=["Salud_Transporte", "Salud_Agua", "Exposicion_Talleres", "Exposicion_Lugares"]
)

# 4. Codificar frecuencias alimentarias (cambiará "Diario", "Nunca" por 4, 0, etc.)
df_procesado = heavystats.encode_dietary_frequencies(df_procesado)

# 5. Seleccionar el metal (conservará las transformaciones anteriores)
df_plomo = heavystats.select_metal(df_procesado, concentration_col="plomo")

# Ver las nuevas columnas generadas y las variables alimentarias
#df_plomo.iloc[:, 35:50]

In [10]:
# Estas pruebas expresan o validan si existe o no balance entre ambas poblaciones.
import heavystats

# 1. Cargar y limpiar
df = heavystats.load_data()
df = heavystats.standardize_boolean_columns(df)

# 2. Obtener el reporte comparativo
report = heavystats.compare_groups(df)

# 3. Renderizar automáticamente (esto mostrará la tabla Markdown formateada en Jupyter)
report